# Generated by Django 5.1.3 on 2026-05-06 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('interested_in', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('education', models.CharField(blank=True, max_length=120)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('profile_video_url', models.URLField(blank=True)),
                ('voice_intro_url', models.URLField(blank=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('personality_type', models.CharField(blank=True, max_length=12)),
                ('relationship_preference', models.CharField(blank=True, max_length=120)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('lifestyle_preferences', models.JSONField(blank=True, default=dict)),
                ('profile_completion', models.PositiveSmallIntegerField(default=10)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
